#!/data/data/com.termux/files/usr/bin/env bash
# install
#

(apt update && apt upgrade -y && apt install ncurses-utils -y) &> /dev/null

ar=( '█■■■■' '■█■■■' '■■█■■' '■■■█■' '■■■■█' )

spin() {
for i in ${ar[@]}
do
    tput civis
    tput cup 10
    echo -ne "\rPlease wait... [$i]"
    sleep 0.05
done
tput cup 10
echo -ne "\rPlease wait... [Done ]"
sleep 1
tput cnorm
}
sleep 1
clear
tput cup 5
tput civis
echo -e "\033[00;92m\rPlease wait... Installing packages \033[0m[\033[00;93mNone\033[0m]"

(apt update && apt install toilet figlet python -y) &> /dev/null
tput civis
tput cup 5
echo -e "\033[00;92m\rPlease wait... Installing packages \033[0m[\033[00;93mDone\033[0m]"
sleep 1

tput cnorm
